### ISSUE TITLE
Game auto rotates even with auto rotate off. 

### ISSUE THREAD

**Issue by ghost** [fexed/Pinball-on-Android#11]
On pixel 6, I have auto rotate off 

However this app ignores that and continues to rotate to match the orientation of the device.  
This makes it difficult to play.

Let me know if more details are needed. 

Love your work ☺️

**Comment by fexed** [comment]
Thanks for the feedback!
I should've fixed this with #7 
The fix will come in a future update, in the upcoming days. After the update let me know if the issue is still present!
Stay tuned!

Edit: the fix is now available in the release 1.2!
