### ISSUE TITLE
Left/Right bumper pressing left/right screen

### ISSUE THREAD

**Issue by Simi2437** [fexed/Pinball-on-Android#17]
Version 1.2: Hello, I would suggest to controll the bumpers with taping left right screen ( If its not your design of choice maybe let user deside in Settings ). Not the small buttons you can easy miss.

**Comment by fexed** [comment]
References #12 and done with https://github.com/fexed/Pinball-on-Android/commit/57145728b68321b6624c40241feb0d929e15e026
