### ISSUE TITLE
Game closes when screen is rotated

### ISSUE THREAD

**Issue by tomrow** [fexed/Pinball-on-Android#23]
The game dies when the screen is rotated on my Tab S8. I would provide a log but I can't find it.

**Comment by fexed** [comment]
I'll try and look into this. Let me know if you can manage to provide a log

**Comment by tomrow** [comment]
I haven't been able to find a log, this app doesn't make a folder in the `/storage/emulated/0/Android/data` folder, nor asks for file permissions, so I'm not sure where it's logging to. Curiously, this issue doesn't occur on my Samsung Galaxy S10+ (Exynos), only the Tab S8.

**Comment by fexed** [comment]
Please let me know if https://github.com/fexed/Pinball-on-Android/releases/tag/1.4 fixes the problem

**Comment by tomrow** [comment]
Sorry, the issue persists in version 1.4.
