### ISSUE TITLE
Flippers control buttons

### ISSUE THREAD

**Issue by niosus** [fexed/Pinball-on-Android#25]
Thanks for this amazing port! The only thing I see could vastly improve it is to assign the flipper buttons to halves of the screens, ditching the dedicated buttons. I'm sometimes missing the button as they are quite small.

**Comment by fexed** [comment]
This has been done and is available in [release 1.3](https://github.com/fexed/Pinball-on-Android/releases/tag/1.3)!

**Comment by niosus** [comment]
Oh, sorry, my bad! Mixed up versions. Thanks a lot!

**Comment by fexed** [comment]
No problem 😁👍🏻
