### ISSUE TITLE
Version 1.3 startup crash

### ISSUE THREAD

**Issue by GX4600** [fexed/Pinball-on-Android#26]
The latest version closes instantly on my LG k51 on Android 11. I tap the thumbnail in the apps list to launch the game and it instantly sends me back to the phone home screen instead.

**Comment by Mizumo-prjkt** [comment]
Same

Huawei Y6s 2019 btw

(My prediction is that this app really didn't call the HWUI Binary where usually OpenGL rests or it's just bad implementation)

**Comment by GustosSelectivos** [comment]
A también no me abre la aplicación, mi móvil es un HUAWEI Y7, y tuve uno similar con la anterior versión siendo que esta se cerraba cada cierto tiempo

**Comment by fexed** [comment]
Will try to look into this, thanks

**Comment by atikattar1104** [comment]
Just Tried On Realme C11 2021 Edition. Same White Screen And Back To Home Screen.

**Comment by Rafaellrg** [comment]
The game also does not open in Galaxy A13 with Android 12.
However, I used version 1.2, and I was amazed at your adaptation work. Congratulations!

**Comment by CyDragon2** [comment]
So far v1.2 works fine but v1.3 well were all knowing what's happening

**Comment by fexed** [comment]
Please let me know if https://github.com/fexed/Pinball-on-Android/releases/tag/1.4 fixes the problem

**Comment by GX4600** [comment]
> Please let me know if https://github.com/fexed/Pinball-on-Android/releases/tag/1.4 fixes the problem

Version 1.4 still startup crashes for me. 😥

**Comment by atikattar1104** [comment]
Tried 1.4 On Redmi 7A. Instead Of White Screen And Crash, App Starts With White Screen, Shows All UI Buttons With Black Background, And Suddenly App Crashes.
Will Test On Realme C11.

**Comment by GX4600** [comment]
Just came by to see if this was fixed, version 2.0 not doing it for me either. Just momentarily looks like it tries to launch and immediately gets sent back to home screen. Same phone same same android version as before. I think I might have some default game launcher app disabled, but I have no idea how to renable it since in the device settings it doesn't let me. Would have to prolly do hard reset of phone and there's just too much work and storage data to jump through that kind of hurdle. Just port the APK to the Google playstore maybe idk, what else to try. :(

**Comment by atikattar1104** [comment]
Version 2.0 Crashes As Well.

**Comment by atikattar1104** [comment]
Version 2.1 Crashes As Well. Tested Few Minutes Ago, Crashes The Same Way As 1.3, 1.4, And 2.0 Crashed.

**Comment by atikattar1104** [comment]
> The game also does not open in Galaxy A13 with Android 12. However, I used version 1.2, and I was amazed at your adaptation work. Congratulations!

1.2 Is Only Working For Me As Well.

**Comment by GX4600** [comment]
Version 2.1 seams to work finally, but I'm unable to download the apk. Can you send it to me please ?

**Comment by GX4600** [comment]
I was really hoping version 2.1 was finally gonna lemme play the game. Turns out the same issue, same os version, phone, all that still a problem. Struggle to download the apk as welll.

**Comment by fexed** [comment]
The main problem is that I haven't been able to reproduce this startup crash, so I frankly haven't the slightest idea what could be causing it. Surely it's an initialization problem, maybe during SDL startup or things like that, but without reproducing it I can't possibly fix this blindly, I am sorry.
If anybody can provide a log of the crash, that would be most useful.

@GX4600 what problem did you encounter in downloading the APK?

**Comment by fexed** [comment]
Still looking into this issue, sorry for the wait but I haven't been able to reproduce it so it's an hard-to-fix issue.

@GX4600 what problem did you encounter when downloading the APK?

**Comment by GX4600** [comment]
I have 3 different ways of downloading on my mobile browser app, built in, system default, and a separate "downloader" add-on. Basically all 3 options return a download failed response. The closest i've come is with the built in option, but it just hangs between 50 % - 75 % of download progress. 

The app is called Via Browser and the add-on is called Advanced Download Manager, one with red green and blue down arrows. 

As for the same startup or launch bug plaguing my experience, I'm just guessing it's a problem on my end somewhere. Still, if I had a proper apk file of the latest version maybe you could see a crash log or system details to try and reproduce the issue on your end.

Message me and I can provide an email for you to send me the apk file, just make sure if possible that it has an option to send a crash log or system details for you to analyze and try to reproduce the issue.

**Comment by GX4600** [comment]
Upgraded phone to Android 12 OS, finally managed to unlock game launcher app, but it still crashes on startup on version 2.1. Idk maybe just upload the full game somewhere downloadable, these apk files just don't wanna lemme play the old space cadet pinball game at this rate. 😥

**Comment by Rafaellrg** [comment]
Hi!Yes, the version 1.4 resolved the crash on my Galaxy A13 with Android 12.Thank you for your willingness to help us!Em 9 de jul de 2022 07:49, GX4600 ***@***.***> escreveu:



Please let me know if https://github.com/fexed/Pinball-on-Android/releases/tag/1.4 fixes the problem



Version 1.4 still startup crashes for me. 😥

**Comment by NyuChan01** [comment]
Only version 1.3 and older works on my Galaxy J4+, probably there's something on the newer versions making it happen.

**Comment by GX4600** [comment]
I recently had to make the difficult decision to just upgrade to a new device. If you guys are still struggling, check out the Nokia G400 5G if your on T-Mobile. Android 12 right out of the box and runs the pinball apk just fine. In the worst case I think most folks might have to factory reset their device and even then theres a chance that might not fix the problem.

**Comment by Mizumo-prjkt** [comment]
> I recently had to make the difficult decision to just upgrade to a new device. If you guys are still struggling, check out the Nokia G400 5G if your on T-Mobile. Android 12 right out of the box and runs the pinball apk just fine. In the worst case I think most folks might have to factory reset their device and even then theres a chance that might not fix the problem.

Recently factory device my phone (Galaxy A12s/A12 Nacho ) same thing (exynos850)

**Comment by fexed** [comment]
Please check if v2.2.1 fixes your problems!

**Comment by atikattar1104** [comment]
v2.4 Works In Redmi 7A. But Have Small Issues Mentioned In #77.

**Comment by Mizumo-prjkt** [comment]
This thread is probably a year old now lol. Anyways is this game fixed? I havent tried the latest version since the 1.3 version blackscreen

**Comment by GX4600** [comment]
> This thread is probably a year old now lol. Anyways is this game fixed? I havent tried the latest version since the 1.3 version blackscreen

I have a pretty basic android 12 phone. The latest version of the game works just fine for me. Download the latest apk of the game and try it out. Let us know how it goes for you.
