### ISSUE TITLE
no number of balls remaining

### ISSUE THREAD

**Issue by atikattar1104** [fexed/Pinball-on-Android#27]
GG, But, Number Of Balls Remaining Is Not Available.

**Comment by fexed** [comment]
Need few more infos on this. Since v1.3 the ball number is shown on the bottom of the screen in portrait mode and in the sidebar in landscape mode. Is that not available?

**Comment by atikattar1104** [comment]
I Mean To Say, In Original Pinball Game On WinXP, I Think There Is 3/3, 2/3, 1/3 Type Of Display To Show How Much Balls Are Remaining. That's What Missing.

**Comment by atikattar1104** [comment]
I Am Able To Use v1.2 (Since v1.3 Is Unable To Run On My Redmi 7A). In That, Even If You Are Playing Your Last Ball, Or Even Game Is Over, It Says "Balls 3". I Think That Issue Is Fixed In v1.3. I'm Not Sure.

**Comment by fexed** [comment]
That's the intended behavior. The games only shows the number of the current ball, with "Ball 3" meaning "you're playing your 3rd ball". That's the original behavior

**Comment by mherrmann3** [comment]
I was also thinking that it would be useful to report how much balls are remaining (also to check if one got an extra/replay ball). I'm aware that this deviates from the original game and may be undesired.

**Comment by fexed** [comment]
Tracking the proposal of @mherrmann3 in #51 to keep things tidy
