### ISSUE TITLE
Configurable control points, or at least have the left/right flippers be controllable through left-half/right-half of whole screen

### ISSUE THREAD

**Issue by in2erval** [fexed/Pinball-on-Android#32]
Hello, first of all thank you for the great port of the game to Android, it's working well on Galaxy S22+.

Currently the controls for the flippers are placed at the bottom of the screen, which makes it very uncomfortable for me to use because I have to bend my thumbs in an awkward way. It gets especially painful when the game duration gets long.

Would it be possible to have a way to move the left/right flipper buttons to different locations of the screen, similar to emulator programs like MyBoy or DraStic?

If not, it would be great if at least the flipper controls are expanded to cover the full vertical screen.

**Comment by fexed** [comment]
The left/right partition of the screen mapped to the two flippers is available in the v1.3
Will look into the possibility of customizing the position of the buttons
