### ISSUE TITLE
Controls are flipped on right to left language devices

### ISSUE THREAD

**Issue by ofekdeu** [fexed/Pinball-on-Android#33]
https://user-images.githubusercontent.com/33030358/176975952-3e963b17-b2a5-470f-b17f-2de2a4b9e600.mp4

As you can see from the video the controls are flipped on devices that are set to a right to left languages such as Hebrew or Arabic, it would be nice if there would be a feature in settings to flip or rearrange the controls.

**Comment by fexed** [comment]
Will fix this! Thanks for letting me know!
