### ISSUE TITLE
Flippers get stuck in up position 

### ISSUE THREAD

**Issue by muddymind** [fexed/Pinball-on-Android#36]
Hi!

In the v1.3 one of the flippers sometimes get stuck in the up position. I can't find a way to consistently replicate it but it just happens from time to time. To correct it I have to touch the corresponding screen side to trigger it and it goes down afterwards.

Btw, thanks for putting the effort to bring back this gem in your free time :)

**Comment by mherrmann3** [comment]
Let me guess: you (also) use Android's [Gesture navigation](https://support.google.com/android/answer/9079644), which makes use of swiping from the left and right edges? This type of navigation seems to somehow interfere with the app's UI, triggering a brief (but not actual) "go back" command and causing the flippers to hold in the 'up' position. I could reproduce it. Some ways to circumvent it:

1. addressing the user
    - try to not tap too close to the left/right edge of your screen; do it more toward the middle;
    - when you cannot help it, try to not move your finger once you tap; just do a "perfect" tap.
2. addressing the dev:
    - try to catch these "almost-go-back" commands and ignore those (no idea how to do that); or
    - check if a flipper is in 'up' position without the user pressing the screen; if so, "reset" the flipper.

**Comment by muddymind** [comment]
Thanks for the feedback. That might be indeed the issue.
I mostly use my 12" tablet to play and doing perfect taps is a bit had to always manage to do since the dimensions of the tablet require a firm grip on it.
