### ISSUE TITLE
La aplicación se sierra

### ISSUE THREAD

**Issue by CR4ZYDANI** [fexed/Pinball-on-Android#42]
Tengo un Xiaomi Redmi 9C
Cuando abro la aplicación se me sierra enseguida, no aparece ninguna imagen, se sierra a instante de abrir la aplicación

**Comment by nathan-hyan** [comment]
Translation for the devs: The app immediately closes after launching the app. This happens with a `Xiaomi Redmi 9C` (And with a `Samsung A02s`)

**Comment by fexed** [comment]
@nathan-hyan thank you
Tracking these issues in #26
