### ISSUE TITLE
If you launch the ball and it barely reaches the first yellow light but then it goes back to the plunger, then the plunger button disappears and you are forced to restart the game.

### ISSUE THREAD

**Issue by Missingphy** [fexed/Pinball-on-Android#44]
Hello, Thank you for porting this from windows to android, truly smart. Just wanted to report this issue that I discovered, as I losy a 3M HS because of this lol. The title explains the issue. Otherwise this work is brilliant, the physics and even the bugs are exactly like on windows, it feels exactly as 13 years ago!

**Comment by dieser-niko** [comment]
The same just happened to me:
![Screenshot_2022-07-20-06-32-34-40_8f7beb5ece72abd63b2d96efe52e9694](https://user-images.githubusercontent.com/26098388/179897759-dc222cbc-2a14-43df-9508-aee0d994e832.jpg)

**Comment by fexed** [comment]
Should be fixed
