### ISSUE TITLE
Ball Physics

### ISSUE THREAD

**Issue by TheSTRAFF** [fexed/Pinball-on-Android#46]
Ball floats around like it's in a gravitational field... 
As if a gust of wind is blowing it around the board

https://user-images.githubusercontent.com/59453520/177397171-3a5d51a7-7e8b-44c5-8c06-7b75be1e772b.mp4

**Comment by fexed** [comment]
Because it is! The red blinking light in the middle is the signal that the gravitational field is activated. Let the ball go on the red light and it will shoot it away in a random direction. It's a feature of the game 👍🏻
