### ISSUE TITLE
Would someone compile this for Android 9?

### ISSUE THREAD

**Issue by jlbdroid** [fexed/Pinball-on-Android#49]
I have not done Android development for a long time so I'm asking if someone would compile this for Android 9. I have a Android based pinball machine powered by a Beelink GT King Android 9 TV box. Version 1.3 doesn't seem to run on Android 9 (or the Beelink box); it force closes upon launch. Can anyone help?
If not I'll have to install the SDK, get correct ROM and try it myself. Was hoping someone might already be set up to compile for Android 9.

**Comment by fexed** [comment]
Will try to do asap

**Comment by jlbdroid** [comment]
Wow really? I'd really appreciate that. Thanks so much for the quick
response too. My virtual pinball has a 22" IPS monitor (not touch screen).
Do you think this apk will work with a keyboard encoder (or BT controller)
as opposed to touching flippers/plunger?

**Comment by jlbdroid** [comment]
Just FYI, from the picture you'll notice pinball.apk will run in Windows 11
WSA/Android and a Xbox controller works with it. But if I try to maximize
Space Cadet, it crashes. I tried with Windows in portrait mode and
landscape mode. But it does play well! Thanks for this port.

**Comment by fexed** [comment]
Next version should be compatible with Android 4 and upward
