### ISSUE TITLE
When I use the cheat for an extra ball, the ball counter for the three 

### ISSUE THREAD

**Issue by BatataChan** [fexed/Pinball-on-Android#50]
When I use the cheat for the extra ball, It works, but the counter tells me which ball I'm using for no 3 and doesn't go up any more than that. I'm on the fifth ball but still q mark is the third.

**Comment by fexed** [comment]
Refer to this answer https://github.com/fexed/Pinball-on-Android/issues/27#issuecomment-1173029932
The game doesn't count the total number of balls but instead it should be interpreted as phases of the game.
It's intended, as it is the original behavior of the game
