### ISSUE TITLE
Disabling custom fonts hides all text on screen

### ISSUE THREAD

**Issue by ebm539** [fexed/Pinball-on-Android#55]
Version 1.4 from the releases page, using the provided APK.

Expected behaviour when custom fonts are disabled (IMO) is to keep text on screen, but use Android's fonts (as version 1.3 does).

**Comment by nen3i** [comment]
Same behaviour for me

**Comment by moecre** [comment]
I think the text is still there but in black color, barely visible. I play on a Retroid Pocket 2+ so having no text on screen at all would be a nice additional option ;) Thanks for this awesome port!
