### ISSUE TITLE
Please please remove/make configurable annoying notification!!

### ISSUE THREAD

**Issue by strlcat** [fexed/Pinball-on-Android#56]
Hi,
I really liked your port cause it brings sweet memories back :-)
But PLEASE remove or make it configurable `Keep pressed on the screen to throw the ball` 3s notification. Really annoying that it cannot be disabled.
I cannot compile app myself cause it suddenly requires latest java for some reason.
Otherwise, thanks, and five ⭐⭐⭐⭐⭐ stars. Excellent!

**Comment by fexed** [comment]
Already present in the future update! Will release it soon, thanks for the kind words!

**Comment by strlcat** [comment]
Ah, sorry then. I see it is duplicate. First time excitement really. 🤩
