### ISSUE TITLE
Occasionally leaderboard server times out, but still loads behind the error

### ISSUE THREAD

**Issue by 9thyear2** [fexed/Pinball-on-Android#62]
![Screenshot_20220821-204414_Space_Cadet_Pinball](https://user-images.githubusercontent.com/29149297/185823179-ccd41bb5-95c9-4c39-8d24-13ebf2fb9b4a.png)

**Comment by fexed** [comment]
I think I found the cause, should be fixed in v2.4 (coming in the future)
