### ISSUE TITLE
is it possible to lower android sdk version requirements?

### ISSUE THREAD

**Issue by rumly111** [fexed/Pinball-on-Android#63]
If I am not wrong, you need Android SDK version 14 for SDL2 program ports (it corresponds to Android 4.0).

So I was wondering why is the minimum SDK version for this project set to 21 (Android 5.0)? Is it possible to lower it to 14 or 15?

**Comment by bman001001** [comment]
Because google has deemed android 4 and below insecure and doon android 5 will share the same fate

**Comment by rumly111** [comment]
I'm glad you and old man google are concerned about the security of my old android tablet, but you have to trust me -- I really don't (and can't) use it to surf the internet or social networks, because it's just that old. I mainly use it to play a few old games and listen to podcasts.
If you make a game that can be compiled on older operating systems with little to no efforts, there are no technical reasons not to support them. It's not like it's a banking app and you can lose your money due to bugs in old Android version.

**Comment by rumly111** [comment]
thanks! when can we expect a release? I'd like to download the up-to-date apk

**Comment by fexed** [comment]
Today! :)

**Comment by rumly111** [comment]
nice. btw I saw some Android-related commits in the upstream repository (Iscle/SpaceCadetPinball). I wonder if they also want to support Android.

EDIT. oh sorry those are old commits, I just saw the date :)
