### ISSUE TITLE
New high score not being stored or uploaded

### ISSUE THREAD

**Issue by SergioVJr** [fexed/Pinball-on-Android#64]
I believe when I updated the app to v2.0, it had uploaded my current high score successfully. But since then I got 2 new ones, with the toast saying it was uploaded, but checking in the settings it shows my old one there and in the actual leaderboards.
I'm not using any cheats, and had a working connection both times.
![Screenshot_20220823-152709](https://user-images.githubusercontent.com/8216044/186312204-efab838a-8dc5-46c5-9a79-cf60569fb258.png)
![Screenshot_20220823-152714](https://user-images.githubusercontent.com/8216044/186312288-d32b2241-5e48-4c07-ac4e-6307a8ea8273.png)

**Comment by LukaTV939** [comment]
Having same issue on v2.1

**Comment by nikolai5slo** [comment]
I'm also having same issue on v2.1

**Comment by fexed** [comment]
Should be fixed in v2.3
