### ISSUE TITLE
Launching impossible after a failed launch 

### ISSUE THREAD

**Issue by DanieleEsposito** [fexed/Pinball-on-Android#65]
If I launch the ball too slowly and the very first light turns on, but the ball doesn't make it through and goes back to the starting launch position, touching the screen will work the flippers and I'm not able to launch the ball anymore.

**Comment by DanieleEsposito** [comment]
![Screenshot_2022-08-31-23-42-52-176_com fexed spacecadetpinball](https://user-images.githubusercontent.com/35259328/187790454-328d3738-8812-452d-9d8f-eed1b1f0624f.jpg)

**Comment by 9thyear2** [comment]
i ran into the same issue, and another weird but similar bug where i was unable to launch the ball (which happens occasionally)

thinking maybe a dedicated launch button as a work around for edge cases would be a good idea

in this first picture its the same as described
![unnamed](https://user-images.githubusercontent.com/29149297/193975381-b684ac72-5828-46c1-8a8b-bac0e29602d6.png)

this second one is sometimes when you lose a ball launching is impossible
![unnamed (1)](https://user-images.githubusercontent.com/29149297/193975389-afd9d745-64c1-45fd-a3f8-0ff74c82774f.png)

**Comment by fexed** [comment]
Added an hideable bottomsheet with a plunger button that should address these cases, hidden by default and activable from the settings. Should be available in v2.3
