### ISSUE TITLE
When using traditional Chinese, control failed and display error

### ISSUE THREAD

**Issue by zyh941** [fexed/Pinball-on-Android#66]
Hello, I just updated app to the latest 2.1 and I switched the app language from English to Traditional Chinese. However, the ball doesn't display and I also can't throw it, nor the left and right board working!(Screenshot 1) And then I go to settings in the app, texts are correct, I go back to the game table. Now it turns ture black!(Screenshot 2) The only thing that works is the translation. Other than that, no errors occurred. It needs to fix this!
Device: Google Pixel 5, running stock Android 13 (TP1A.220905.004)
<img width="540" alt="no ball" src="https://user-images.githubusercontent.com/95530307/190356818-ca9cbcdd-0c86-46cc-81c6-336e487a76ed.png">
![go black](https://user-images.githubusercontent.com/95530307/190356900-e74affd5-5703-43ba-a761-51bdd74cca4c.png)

**Comment by Bob-YsPan** [comment]
Hmm...
I found the same problem when I test it myself...
A log file I record is here...

But I can't find the clue what cause it...

[pinball_stuck.log](https://github.com/fexed/Pinball-on-Android/files/9575761/pinball_stuck.log)

**Comment by zyh941** [comment]
I don’t know either because I am not a code engineer…, waiting for other’s help.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Bob-YsPan** [comment]
I check my resource
Seems the translation file the line number are same as original English version...

I re-record the logcat via the Process ID and switches the language to English(English version still work... weird...)
The logcats uploads here, I cannot find some clue at these two files.

[pinball_stuck_PID.log](https://github.com/fexed/Pinball-on-Android/files/9576343/pinball_stuck_PID.log)
[pinball_eng_PID.log](https://github.com/fexed/Pinball-on-Android/files/9576344/pinball_eng_PID.log)
(My phone is Galaxy A52s running Android 12)

**Comment by HarGabt** [comment]
Same problem when switching language to Russian - the game softlocks in the same way as in the original post

**Comment by fexed** [comment]
It seems that in-game texts with non-latin characters breaks the game. I am publishing version 2.2.1 that removes the localized in-game messages while waiting to figure out how to handle this.

In the meantime I will use issue #73 to track this problem
