### ISSUE TITLE
Game freezes with non-latin texts

### ISSUE THREAD

**Issue by zxcdjilyt** [fexed/Pinball-on-Android#73]
(sorry for bad english btw) when im trying to start the game, and ball trying to appear, the game just freezes, and when i trying to restart, it still not working. after opening and exiting settings the game is turning into a black screen.
idk what to do 😶
phone: Samsung Galaxy S8+
![Screenshot_20230116-195546_Space Cadet Pinball](https://user-images.githubusercontent.com/122816675/212731097-e07023ff-f6db-4b5b-b949-12fdd44fe5a6.jpg)
⬆️⬆️⬆️
freezing at this moment
![Screenshot_20230116-195556_Space Cadet Pinball](https://user-images.githubusercontent.com/122816675/212731115-4123778b-c3f2-4def-ab11-34188c3945ca.jpg)
⬆️⬆️⬆️after entering and exitng the settings menu

**Comment by Melodeiro** [comment]
Confirm for the 2.1 version. Downgrading to 2.0 solved the problem for me. Android 13, OnePlus 9 pro

**Comment by zxcdjilyt** [comment]
tysm!!!😁 its works perfectly!

**Comment by HarGabt** [comment]
[The latest 2.2 release](https://github.com/fexed/Pinball-on-Android/releases/tag/2.2) hasn't solved the problem. 

So, yeah, either resort to 2.0 version without localisations, or switch the UI language on your device to English.
Or maybe, implement UI language switch in the port.

**Comment by fexed** [comment]
It seems that in-game texts with non-latin characters breaks the game. I am publishing version 2.2.1 that removes the localized in-game messages while waiting to figure out how to handle this.

**Comment by Bob-YsPan** [comment]
> It seems that in-game texts with non-latin characters breaks the game. I am publishing version 2.2.1 that removes the localized in-game messages while waiting to figure out how to handle this.

Recently when I was playing this game, I realized that when you rotate the screen, a table with a score and status interface will appear.

![Screenshot_20231222_161922_Space Cadet Pinball](https://github.com/fexed/Pinball-on-Android/assets/46966555/8571b6e3-263c-41e0-bcc6-dddbddc36001)

So I wonder if the reason for the freeze is that non-Latin characters can't access the bitmap text in the status interface, but I'm not very sure if the program tries to read the bitmap text when on the vertical screen mode.

This is the example of the Chinese Version of the game with full interface on the Windows, as you can see the non-Latin charaters 
 still use the system font and not load the bitmap font

(Picture from [Soft4fun Site](https://www.soft4fun.net/how-to/tips/3d-pinball-secret-game-never-end.htm))
![image](https://github.com/fexed/Pinball-on-Android/assets/46966555/fb93a920-7eac-4a1b-aec5-7c95c7713a1f)
