### ISSUE TITLE
Move Pause button to upper left corner

### ISSUE THREAD

**Issue by SpaceXCheeseWheel** [fexed/Pinball-on-Android#75]
I think that the current location of the pause button obstructs the view of the bottom of the board too much. I suggest it gets moved up to the top right of the screen, in between the pause/reset button and the information text. Below is a mockup. I do have a fairly large phone screen; I'm not sure if this will cause any undesirable effects on smaller screens. 
![image](https://user-images.githubusercontent.com/12452268/224513464-f6d8b8fd-814a-48c9-8fb0-9e5d35ff7ee5.png)

**Comment by fexed** [comment]
I think it is a good Idea but I prefer keeping the top text centered, so I will try moving the pause button *below* the replay button. The table shrinks going up so there shouldn't be any problems. To keep symmetry, the cheat indicator will be moved below the settings button.
